(() => {
  const LS_LANG = 'lang';
  const LS_THEME = 'theme';

  /* =====================
     TRANSLATIONS
     ===================== */
  const translations = {
    ru: {
      // NAV
      nav_home: 'Главная',
      nav_catalog: 'Каталог',
      nav_services: 'Услуги',
      nav_contacts: 'Контакты',
      nav_calculator: 'Калькулятор',
      nav_login: 'Войти',
      nav_account: 'Личный кабинет',
      nav_not_verified: 'не подтверждён',
      nav_logout_confirm: 'Выйти из аккаунта?',
      title_register: 'China Motors - Регистрация',
      title_login: 'China Motors - Вход',
      register_hero: 'Регистрация',
      register_tagline: 'Создайте аккаунт клиента China Motors',
      register_tab_person: 'Физ. лицо',
      register_tab_company: 'Юр. лицо',
      register_person_note: 'Физ. лицо может приобрести легковой автомобиль. Для коммерческой техники используйте регистрацию юр. лица.',
      register_company_note: 'Юр. лица могут приобретать коммерческую технику разных видов.',
      register_phone_label: 'Телефон',
      register_password_label: 'Пароль',
      register_fullname_label: 'ФИО',
      register_iin_label: 'ИИН (для договора)',
      register_companyname_label: 'Название компании',
      register_bin_label: 'БИН (для договора)',
      register_address_label: 'Юридический адрес',
      register_submit: 'Создать аккаунт',
      register_have_account: 'Уже есть аккаунт? Войти',
      register_err_required: 'Заполните обязательные поля',
      register_success: 'Регистрация завершена! Аккаунт ожидает подтверждения администратором.',
      login_hero: 'Вход',
      login_tagline: 'Войдите в личный кабинет China Motors',
      login_submit: 'Войти',
      login_no_account: 'Нет аккаунта? Зарегистрироваться',
      login_success: 'Вход выполнен!',
      register_tab_service: 'Сервисный партнёр (СВХ)',
      register_tab_bank: 'Банк',
      register_tab_partner: 'Партнёр-продавец (Китай)',
      register_service_note: 'Выберите роль. Аккаунт будет ожидать подтверждения администратора.',
      register_service_role_label: 'Роль',
      register_service_role_placeholder: '— выбрать —',
      register_role_declarant: 'Декларант (граница)',
      register_role_logistic: 'Логист',
      register_role_lab: 'Лаборатория',
      register_role_svh: 'СВХ',
      register_role_broker: 'Брокер (СВХ)',
      register_bank_note: 'Аккаунт банка используется для сопровождения расчётов по сделке.',
      register_bankname_label: 'Название банка',
      register_bik_label: 'БИК',
      register_partner_note: 'Партнёр получает кабинет и загружает объявления техники — они проходят модерацию администратора.',
      register_country_label: 'Страна',
      register_regno_label: 'Регистрационный номер компании (для договора)',
      title_account: 'China Motors - Личный кабинет',
      account_hero: 'Личный кабинет',
      account_logout: 'Выйти',
      account_loading: 'Загрузка...',
      account_my_listings_title: 'Мои объявления',
      account_new_listing: 'Разместить объявление',
      account_listing_brand_label: 'Бренд',
      account_listing_title_label: 'Название / модель',
      account_listing_category_label: 'Категория',
      account_listing_city_label: 'Город',
      account_listing_weight_label: 'Масса, т',
      account_listing_power_label: 'Мощность двигателя, л.с.',
      account_listing_load_capacity_label: 'Грузоподъёмность, т',
      account_listing_price_kzt_label: 'Цена, ₸',
      account_listing_photos_label: 'Фото',
      account_listing_description_label: 'Описание',
      badge_user_listing_prefix: 'Объявление от',
      product_create_deal: 'Оформить сделку',

      // COMMON
      brand_title: 'China Motors',
      hero_title_main: 'Спецтехника и автомобили из Китая под ключ',
      hero_tagline: 'Подбор • расчёт • доставка • таможня • постановка на учёт в РК',
      hp_hero_badge: 'ПРЯМЫЕ ПОСТАВКИ ОТ ЗАВОДОВ КИТАЯ',
      hp_bullet1: 'Официальный договор',
      hp_bullet2: 'Банк защищает деньги',
      hp_bullet3: 'Полный комплект документов',
      hp_bullet4: 'С 2018 года',
      hp_cta_offer: 'Получить КП',
      hp_cta_catalog: 'Смотреть каталог →',
      hp_calc_widget_title: 'Рассчитать стоимость',
      hp_calc_category: 'Категория',
      hp_calc_brand: 'Марка',
      hp_calc_submit: 'Рассчитать стоимость',
      hp_calc_widget_note: 'бесплатно и ни к чему не обязывает',
      hp_process_title: 'Как проходит сделка',
      hp_step1_t: 'Выбор техники',
      hp_step1_d: 'Подбираем модель под задачи и бюджет',
      hp_step2_t: 'Коммерческое предложение',
      hp_step2_d: 'Расчёт стоимости с полной спецификацией',
      hp_step3_t: 'Договор и оплата',
      hp_step3_d: 'Безопасная оплата через банк, полный пакет документов',
      hp_step4_t: 'Поставка и растаможка',
      hp_step4_d: 'Логистика из Китая и таможенное оформление',
      hp_step5_t: 'Получение техники',
      hp_step5_d: 'Передача техники и полный комплект документов',
      hp_vehicles_title: 'Популярная техника',
      hp_vehicles_link: 'Смотреть весь каталог →',
      hp_vehicles_loading: 'Загрузка...',
      hp_vehicle_cta: 'Получить КП',
      hp_stats_label: 'НАМ ДОВЕРЯЮТ',
      hp_stat1: 'клиентов',
      hp_stat2: 'заводов-партнёров',
      hp_stat3: 'единиц техники',
      hp_stat4: 'работы',
      hp_stat4_years: 'лет',
      footer_address_khorgos: 'г. Хоргос — склад и отгрузка',
      footer_address_almaty: 'г. Алматы — выдача техники',
      footer_col1_text: 'Надежная техника из Китая под заказ и в наличии.',
      footer_col2_title: 'Навигация',
      footer_col3_title: 'Контакты',
      footer_copy: '© 2026 China Motors. Все права защищены.',
      footer_devnote: 'Информация на сайте носит справочный характер и не является публичной офертой',
      btn_photos: 'Фотографии',
      btn_calculate: 'Рассчитать',
      btn_send: 'Отправить',
      btn_refresh_rate: 'Обновить курс',
      search_placeholder: 'Поиск...',

      // INDEX
      about_title: 'О нас',
      about_p1: 'China Motors — ваш надежный партнер в поставке автомобилей и спецтехники из Китая города Хоргос. С 2024 года мы предлагаем качественные машины и профессиональные услуги по доставке и таможенному оформлению.',
      about_p2: 'Наша миссия — обеспечить клиентов современной техникой по доступным ценам с гарантией качества.',
      about_card1_t: 'Широкий выбор техники',
      about_card1_d: 'Много различных моделей спецтехники.',
      about_card2_t: 'Индивидуальный подход',
      about_card2_d: 'Учитываем все пожелания клиентов.',
      about_card3_t: 'Надежная доставка',
      about_card3_d: 'С Хоргоса до города Алматы.',
      about_card4_t: 'Прозрачное оформление',
      about_card4_d: 'Полное сопровождение документов.',
      about_card5_t: 'Цена',
      about_card5_d: 'Низкая наценка.',
      gallery_title: 'Галерея',
      gallery_cap1: 'Прицепы',
      gallery_cap2: 'Полуприцепы',
      gallery_cap3: 'Тралы',
      gallery_cap4: 'Самосвалы',
      gallery_cap5: 'Тягачи',
      gallery_cap6: 'Спецтехника',
      gallery_cap7: 'Другие машины под заказ',
      reviews_title: 'Отзывы',
      reviews_title1: 'Техника у клиента',
      reviews_title2: 'Клиент с новым автомобилем',
      reviews_title3: 'Отзыв клиента о доставке тягача',

      // CATALOG
      title_catalog: 'China Motors - Каталог',
      catalog_hero: 'Актуальные предложения из базы',
      filter_body_label: 'Тип транспорта',
      filter_source_label: 'Источник',
      filter_source_all: 'Все объявления',
      filter_source_official: 'Официальный каталог',
      filter_source_user: 'Объявления клиентов',
      filter_sort_label: 'Сортировка',
      sort_none: 'Без сортировки',
      sort_price_asc: 'Цена ↑',
      sort_price_desc: 'Цена ↓',
      card_body_label: 'Тип транспорта:',
      card_wheel_formula_label: 'Колёсная формула:',
      card_gearbox_label: 'КПП:',
      price_on_request: 'Цена уточняется',

      // SERVICES
      title_services: 'China Motors - Услуги',
      services_hero: 'Наши услуги',
      services_tagline: 'Комплексные решения для поставки и обслуживания техники',
      services_title: 'Услуги',
      service_1_t: 'Заказ и поставка',
      service_1_d: 'Автомобили и спецтехника из Китая под ваши нужды.',
      service_2_t: 'Таможенное оформление',
      service_2_d: 'Помощь с таможенной очисткой.',
      service_3_t: 'Доставка',
      service_3_d: 'Доставка с Хоргоса в Алматы (Платные водители).',
      service_4_t: 'Гос. номер',
      service_4_d: 'Помощь с получением Гос. номера.',

      // CALCULATOR
      title_calculator: 'China Motors - Калькулятор',
      calculator_hero: 'Калькулятор',
      calculator_tagline: 'Подбор, доставка и оформление под ключ — рассчитайте стоимость за 2 минуты',
      calc_page_title: 'Калькулятор стоимости',
      calc_in_title: 'Входные данные',
      calc_in_name_label: 'Модель / комплектация',
      calc_in_name_ph: 'Например: Тягач 2022 года',
      calc_in_price_label: 'Цена авто, $',
      calc_in_price_ph: '59165',
      calc_in_type_label: 'Тип транспорта',
      calc_in_rate_label: 'Курс $ → ₸',
      calc_rate_info: 'Курс НБ РК: —',
      calc_real_title: '1) Реальная стоимость',
      calc_real_hint: 'Цена авто в тенге = Цена($) × Курс',
      calc_ts_title: '2) Таможенная стоимость',
      calc_ts_mode: 'Способ расчёта ТС',
      calc_mode_byprice: 'По полной цене',
      calc_mode_grid: 'Сетка (год)',
      calc_mode_fixed: 'Фиксированная сетка',
      calc_ts_usd_manual: 'ТС, $ (для «Фиксированной сетки»)',
      calc_ts_year_label: 'Год (для «Сетка (год)»)',
      calc_ts_year_usd: 'Фиксированная сумма ТС, $',
      calc_ts_bill_title: 'Таможенные платежи',
      calc_ts_bill_ts: 'ТС в тенге',
      calc_ts_bill_duty: 'Пошлина',
      calc_ts_bill_vat: 'НДС',
      calc_mand_title: '3) Дополнительные расходы',
      calc_mand_note: 'Фиксируется по типу транспорта и выбранному режиму ТС.',
      calc_mand_list_title: 'За что платим',
      calc_ship_title: '4) Доставка и граница',
      calc_ship_list_title: 'Состав доставки',
      calc_util_title: '5) Утилизационный сбор и регистрация',
      calc_util_list_title: 'Государственные платежи',
      aside_title: 'Итоговая стоимость',
      aside_base: 'База для расчёта:',
      aside_customs: 'Таможенные платежи:',
      aside_mand: 'Дополнительные расходы:',
      aside_border: 'Доставка и граница:',
      aside_util: 'Утиль/регистрация:',
      aside_total: 'ИТОГО:',
      aside_usd: '≈ — USD',
      aside_btn_calc: 'Рассчитать',
      aside_btn_apply: 'Оформить заявку',

      // CONTACTS
      title_contacts: 'China Motors - Контакты',
      contacts_hero: 'Контакты',
      contacts_tagline: 'Свяжитесь с нами удобным способом',
      contact_title: 'Оставьте заявку',
      contact_name_label: 'Ваше имя',
      contact_name_ph: 'Введите имя',
      contact_phone_label: 'Телефон',
      contact_phone_ph: '+7 (___) ___-__-__',
      contact_msg_label: 'Сообщение',
      contact_msg_ph: 'Ваше сообщение',
      contact_note: 'После нажатия «Отправить» заявка сразу попадёт нам в Telegram',

      // JS messages
      js_price_on_request: 'Цена по запросу',
      js_form_err_phone: 'Укажите корректный телефон',
      js_form_err_msg: 'Добавьте сообщение',
      js_form_sending: 'Отправляем...',
      js_form_sent_ok: 'Заявка отправлена! Свяжемся с вами.',
      js_form_sent_fail: 'Ошибка отправки. Попробуйте позже.',
      why_title : 'Почему нам доверяют',
      why_card1_t : 'Работа по договору',
      why_card1_d : 'Все поставки оформляются официально. Прозрачные условия без скрытых платежей.',
      why_card2_t : 'Реальные поставки',
      why_card2_d : 'Работаем с реальной техникой. Фото и видео с погрузки, склада и доставки.',
      why_card3_t : 'Прозрачный расчёт',
      why_card3_d : 'Калькулятор показывает, за что вы платите. Без «потом доплатите ещё».',
      why_card4_t : 'Подбор под бюджет',
      why_card4_d : 'Подбираем технику под задачу и бюджет, а не продаём «что есть».',
      why_card5_t : 'Сопровождение до регистрации',
      why_card5_d : 'Помогаем с документами, таможней и постановкой на учёт.',
      footer_terms: 'Пользовательское соглашение',
      footer_privacy: 'Политика конфиденциальности',
      loading: 'Загрузка...',
      loading_error: 'Ошибка загрузки каталога',

      body_all: 'Все типы',
      body_trailer: "Прицепы",
      body_semitrailer: "Полуприцепы",
      body_dumptruck: "Самосвал",
      body_tugboat: "Тягач",

      body_specialequipment: "Спец. техника",
      body_crane: "Кран",
      body_manipulator: "Манипулятор",
      body_mixer: "Миксер",
      body_fuel_tank: "Бензовоз",
      body_aerial_ladder: "Автовышка",
      body_sewer_cleaner: "Ассенизатор",

      body_refrigerator: "Рефрижератор",
      body_van: "Автофургон",
      body_sprinkler: "Поливомоечная машина",

      body_drilling_rig: "Ямобур машины для бурения",
      body_milk_truck: "Молоковоз",
      body_fuel_truck: "Топливозаправщик",

      calc_item_sbkts: 'СБКТС',
      calc_item_sos: 'Кнопка SOS',
      calc_item_customs_fee: 'Таможенный сбор',
      calc_item_broker_svh: 'Услуги брокера на СВХ',
      calc_item_svh: 'СВХ',
      calc_item_border_broker: 'Брокер на границе',
      calc_item_epts: 'ЭПТС',
      calc_item_diesel_pack: 'Солярка + AdBlue пакет',
      calc_item_red_corridor: 'Коридор',
      calc_item_thanks_astana: '«Спасибо Астане»',
      calc_item_driver: 'Водитель',
      calc_item_insurance: 'Страховка',
      calc_item_toll_road: 'Платная дорога',

      calc_item_declaration: 'Декларация о соответствии',
      calc_item_customs_broker: 'Таможенный брокер',
      calc_item_driver: 'Водитель',
      calc_item_adblue: 'AdBlue',
      calc_item_toll_road: 'Платная дорога',
      calc_item_diesel: 'Солярка',
      calc_item_plate: 'Госномер и техпаспорт',
      calc_item_util_tax: 'Утилизационный сбор',
      calc_item_first_reg: 'Первичная регистрация',
      calc_item_srtc: 'Техпаспорт (СРТС)',
      calc_flag_intl_carrier: 'Есть удостоверение международного перевозчика (первичная регистрация не взимается для тягачей до 7 лет)',


      // TOTAL LABELS
      calc_total_vehicle: 'Стоимость авто',
      calc_total_clearance: 'Стоимость оформления',
      calc_total_turnkey: 'Итого под ключ',
      calc_year_label: 'Год выпуска',
      calc_item_broker_service: 'Услуги Брокера на СВХ',
      calc_disclaimer: '⚠️ Расчёт является предварительным и не является публичной офертой. Итоговая стоимость зависит от курса валют, таможенных платежей и условий поставки. Подробности уточняйте у менеджера.',
      body_car: 'Легковой автомобиль',
      calc_ts_bill_duty_percent: 'Ставка пошлины',
      why_card1_y: '✔ Работа по договору',
      why_card2_y: '✔ Фото и видео с погрузки и доставки',
      why_card3_y: '✔ Прозрачный расчёт без «вдруг доплатите»',
      why_card4_y: '✔ Помощь с таможней и регистрацией',
      btn_calculate_catalog: 'Подробнее и расчёт',
    },

    kk: {
      reviews_title1: 'Клиент орнындағы жабдық',
      reviews_title2: 'Жаңа көлігі бар тұтынушы',
      reviews_title3: 'Жүк көлігін жеткізу туралы тұтынушылардың кері байланысы',
      nav_home: 'Басты бет',
      nav_catalog: 'Каталог',
      nav_services: 'Қызметтер',
      nav_contacts: 'Байланыс',
      nav_calculator: 'Калькулятор',
      nav_login: 'Кіру',
      nav_account: 'Жеке кабинет',
      nav_not_verified: 'расталмаған',
      nav_logout_confirm: 'Аккаунттан шығу керек пе?',
      title_register: 'China Motors - Тіркелу',
      title_login: 'China Motors - Кіру',
      register_hero: 'Тіркелу',
      register_tagline: 'China Motors клиент аккаунтын жасаңыз',
      register_tab_person: 'Жеке тұлға',
      register_tab_company: 'Заңды тұлға',
      register_person_note: 'Жеке тұлға жеңіл автокөлік сатып ала алады. Коммерциялық техника үшін заңды тұлға ретінде тіркеліңіз.',
      register_company_note: 'Заңды тұлғалар әртүрлі коммерциялық техниканы сатып ала алады.',
      register_phone_label: 'Телефон',
      register_password_label: 'Құпия сөз',
      register_fullname_label: 'Аты-жөні',
      register_iin_label: 'ЖСН (келісімшарт үшін)',
      register_companyname_label: 'Компания атауы',
      register_bin_label: 'БСН (келісімшарт үшін)',
      register_address_label: 'Заңды мекенжай',
      register_submit: 'Аккаунт жасау',
      register_have_account: 'Аккаунтыңыз бар ма? Кіру',
      register_err_required: 'Міндетті өрістерді толтырыңыз',
      register_success: 'Тіркелу аяқталды! Аккаунт әкімші растауын күтуде.',
      login_hero: 'Кіру',
      login_tagline: 'China Motors жеке кабинетіне кіріңіз',
      login_submit: 'Кіру',
      login_no_account: 'Аккаунтыңыз жоқ па? Тіркелу',
      login_success: 'Кіру сәтті өтті!',
      register_tab_service: 'Сервистік серіктес (СВХ)',
      register_tab_bank: 'Банк',
      register_tab_partner: 'Серіктес-сатушы (Қытай)',
      register_service_note: 'Рөлді таңдаңыз. Аккаунт әкімші растауын күтеді.',
      register_service_role_label: 'Рөл',
      register_service_role_placeholder: '— таңдау —',
      register_role_declarant: 'Декларант (шекара)',
      register_role_logistic: 'Логист',
      register_role_lab: 'Зертхана',
      register_role_svh: 'СВХ',
      register_role_broker: 'Брокер (СВХ)',
      register_bank_note: 'Банк аккаунты мәміле бойынша есеп айырысуды сүйемелдеу үшін қолданылады.',
      register_bankname_label: 'Банк атауы',
      register_bik_label: 'БСК',
      register_partner_note: 'Серіктес кабинет алады және техника хабарландыруларын жүктейді — олар әкімші модерациясынан өтеді.',
      register_country_label: 'Ел',
      register_regno_label: 'Компанияның тіркеу нөмірі (келісімшарт үшін)',
      title_account: 'China Motors - Жеке кабинет',
      account_hero: 'Жеке кабинет',
      account_logout: 'Шығу',
      account_loading: 'Жүктелуде...',
      account_my_listings_title: 'Менің хабарландыруларым',
      account_new_listing: 'Хабарландыру орналастыру',
      account_listing_brand_label: 'Бренд',
      account_listing_title_label: 'Атауы / моделі',
      account_listing_category_label: 'Санаты',
      account_listing_city_label: 'Қала',
      account_listing_weight_label: 'Салмағы, т',
      account_listing_power_label: 'Қозғалтқыш қуаты, а.к.',
      account_listing_load_capacity_label: 'Жүк көтергіштігі, т',
      account_listing_price_kzt_label: 'Бағасы, ₸',
      account_listing_photos_label: 'Фотосуреттер',
      account_listing_description_label: 'Сипаттама',
      badge_user_listing_prefix: 'Хабарландыру:',
      product_create_deal: 'Мәміле рәсімдеу',

      brand_title: 'China Motors',
      hero_title_main: 'Қытайдан арнайы техника мен автомобильдер, кілт тапсыру форматында',
      hero_tagline: 'Таңдау • есептеу • жеткізу • кеден • ҚР-да есепке қою',
      hp_hero_badge: 'ҚЫТАЙ ЗАУЫТТАРЫНАН ТІКЕЛЕЙ ЖЕТКІЗУ',
      hp_bullet1: 'Ресми шарт',
      hp_bullet2: 'Ақшаны банк қорғайды',
      hp_bullet3: 'Құжаттардың толық жинағы',
      hp_bullet4: '2018 жылдан бері',
      hp_cta_offer: 'КП алу',
      hp_cta_catalog: 'Каталогты қарау →',
      hp_calc_widget_title: 'Құнын есептеу',
      hp_calc_category: 'Санат',
      hp_calc_brand: 'Марка',
      hp_calc_submit: 'Құнын есептеу',
      hp_calc_widget_note: 'тегін және еш нәрсеге міндеттемейді',
      hp_process_title: 'Мәміле қалай өтеді',
      hp_step1_t: 'Техниканы таңдау',
      hp_step1_d: 'Міндеттер мен бюджетке сай модель таңдаймыз',
      hp_step2_t: 'Коммерциялық ұсыныс',
      hp_step2_d: 'Толық спецификациямен құнын есептеу',
      hp_step3_t: 'Шарт және төлем',
      hp_step3_d: 'Банк арқылы қауіпсіз төлем, құжаттардың толық жинағы',
      hp_step4_t: 'Жеткізу және кеденнен өткізу',
      hp_step4_d: 'Қытайдан логистика және кедендік ресімдеу',
      hp_step5_t: 'Техниканы алу',
      hp_step5_d: 'Техниканы беру және құжаттардың толық жинағы',
      hp_vehicles_title: 'Танымал техника',
      hp_vehicles_link: 'Барлық каталогты қарау →',
      hp_vehicles_loading: 'Жүктелуде...',
      hp_vehicle_cta: 'КП алу',
      hp_stats_label: 'БІЗГЕ СЕНЕДІ',
      hp_stat1: 'клиент',
      hp_stat2: 'серіктес зауыт',
      hp_stat3: 'бірлік техника',
      hp_stat4: 'жұмыс',
      hp_stat4_years: 'жыл',
      footer_address_khorgos: 'Хоргос қ. — қойма және жөнелту',
      footer_address_almaty: 'Алматы қ. — техниканы беру',
      footer_col1_text: 'Қытайдан тапсырыспен және қолжетімді техника.',
      footer_col2_title: 'Навигация',
      footer_col3_title: 'Байланыс',
      footer_copy: '© 2026 China Motors. Барлық құқықтар қорғалған.',
      footer_devnote: 'Сайттағы ақпарат анықтамалық сипатта болып табылады және ашық ұсыныс емес',
      btn_photos: 'Фотосуреттер',
      btn_calculate: 'Есептеу',
      btn_send: 'Жіберу',
      btn_refresh_rate: 'Курсты жаңарту',
      search_placeholder: 'Іздеу...',

      about_title: 'Біз туралы',
      about_p1: 'China Motors — Қорғас қаласынан Қытай техникасын жеткізетін сенімді серіктес. 2024 жылдан бері сапалы көліктер мен кедендік рәсімдеуге көмектесеміз.',
      about_p2: 'Миссиямыз — клиенттерді қолжетімді бағамен сапалы техникамен қамтамасыз ету.',
      about_card1_t: 'Кең таңдау',
      about_card1_d: 'Әртүрлі арнайы техника модельдері.',
      about_card2_t: 'Жеке тәсіл',
      about_card2_d: 'Клиент қалауы ескеріледі.',
      about_card3_t: 'Сенімді жеткізу',
      about_card3_d: 'Қорғастан Алматыға дейін.',
      about_card4_t: 'Мөлдір рәсімдеу',
      about_card4_d: 'Құжаттарды толық сүйемелдеу.',
      about_card5_t: 'Баға',
      about_card5_d: 'Төмен үстеме.',
      gallery_title: 'Галерея',
      gallery_cap1: 'Тіркемелер',
      gallery_cap2: 'Жартылай тіркемелер',
      gallery_cap3: 'Тралдар',
      gallery_cap4: 'Самосвалдар',
      gallery_cap5: 'Тягачтар',
      gallery_cap6: 'Арнайы техника',
      gallery_cap7: 'Тапсырыспен басқа көліктер',

      title_catalog: 'China Motors - Каталог',
      catalog_hero: 'Деректер базасындағы өзекті ұсыныстар',
      filter_body_label: 'Көлік түрі',
      filter_source_label: 'Дереккөз',
      filter_source_all: 'Барлық хабарландырулар',
      filter_source_official: 'Ресми каталог',
      filter_source_user: 'Клиенттердің хабарландырулары',
      filter_sort_label: 'Сұрыптау',
      sort_none: 'Сұрыптаусыз',
      sort_price_asc: 'Баға ↑',
      sort_price_desc: 'Баға ↓',
      card_body_label: 'Көлік түрі:',
      card_wheel_formula_label: 'Дөңгелек формуласы:',
      card_gearbox_label: 'Қорап:',
      price_on_request: 'Баға сұраныс бойынша',

      title_services: 'China Motors - Қызметтер',
      services_hero: 'Біздің қызметтер',
      services_tagline: 'Жеткізу және қызмет көрсетуге кешенді шешімдер',
      services_title: 'Қызметтер',
      service_1_t: 'Тапсырыс және жеткізу',
      service_1_d: 'Қажетіңізге сай Қытайдан техника.',
      service_2_t: 'Кедендік рәсімдеу',
      service_2_d: 'Кедендік рәсімдеуге көмек.',
      service_3_t: 'Жеткізу',
      service_3_d: 'Қорғастан Алматыға (ақылы жүргізушілер).',
      service_4_t: 'Мем. нөмір',
      service_4_d: 'Мемлекеттік нөмір алуға көмек.',

      title_calculator: 'China Motors - Калькулятор',
      calculator_hero: 'Калькулятор',
      calculator_tagline: 'Тапсырыс беру, жеткізу және рәсімдеу — 2 минутта құнын есептеңіз',
      calc_page_title: 'Құн калькуляторы',
      calc_in_title: 'Енгізу деректері',
      calc_in_name_label: 'Модель / жабдықталымы',
      calc_in_name_ph: 'Мысалы: Тягач 2022',
      calc_in_price_label: 'Көлік бағасы, $',
      calc_in_price_ph: '59165',
      calc_in_type_label: 'Көлік түрі',
      calc_in_rate_label: 'Курс $ → ₸',
      calc_rate_info: 'ҰБК курсы: —',
      calc_real_title: '1) Нақты құн',
      calc_real_hint: 'Теңгедегі баға = $ × курс',
      calc_ts_title: '2) Кедендік құн',
      calc_ts_mode: 'Кеден әдісі',
      calc_mode_byprice: 'Толық бағамен',
      calc_mode_grid: 'Тор (жыл)',
      calc_mode_fixed: 'Бекітілген тор',
      calc_ts_usd_manual: 'Кеден $, «Бекітілген тор» үшін',
      calc_ts_year_label: 'Жыл (Тор үшін)',
      calc_ts_year_usd: 'Бекітілген сома, $',
      calc_ts_bill_title: 'Кеден төлемдері',
      calc_ts_bill_ts: 'Кедендік құн (₸)',
      calc_ts_bill_duty: 'Баж',
      calc_ts_bill_vat: 'ҚҚС',
      calc_mand_title: '3) Қосымша шығындар',
      calc_mand_note: 'Көлік түрі және әдіске тәуелді.',
      calc_mand_list_title: 'Төлем құрамы',
      calc_ship_title: '4) Жеткізу және шекара',
      calc_ship_list_title: 'Құрамы',
      calc_util_title: '5) Утильалым және тіркеу',
      calc_util_list_title: 'Мемлекеттік төлемдер',
      aside_title: 'Жалпы құн',
      aside_base: 'Есеп негізі:',
      aside_customs: 'Кеден төлемдері:',
      aside_mand: 'Қосымша шығындар:',
      aside_border: 'Жеткізу және шекара:',
      aside_util: 'Утиль/тіркеу:',
      aside_total: 'ЖИЫНТЫҚ:',
      aside_usd: '≈ — USD',
      aside_btn_calc: 'Есептеу',
      aside_btn_apply: 'Өтінім беру',

      title_contacts: 'China Motors - Байланыс',
      contacts_hero: 'Байланыс',
      contacts_tagline: 'Бізбен ыңғайлы тәсілмен байланысыңыз',
      contact_title: 'Өтінім қалдырыңыз',
      contact_name_label: 'Атыңыз',
      contact_name_ph: 'Атыңызды енгізіңіз',
      contact_phone_label: 'Телефон',
      contact_phone_ph: '+7 (___) ___-__-__',
      contact_msg_label: 'Хабарлама',
      contact_msg_ph: 'Сіздің хабарламаңыз',
      contact_note: '«Жіберу» батырмасынан кейін өтінім Telegram-ға түседі',

      js_price_on_request: 'Баға сұраныс бойынша',
      js_form_err_phone: 'Дұрыс телефон нөмірін көрсетіңіз',
      js_form_err_msg: 'Хабарлама қосыңыз',
      js_form_sending: 'Жіберілуде...',
      js_form_sent_ok: 'Өтінім жіберілді! Байланысамыз.',
      js_form_sent_fail: 'Жіберу қатесі. Кейінірек көріңіз.',
      why_title : 'Неліктен бізге сенеді',
      why_card1_t : 'Келісімшарт бойынша жұмыс',
      why_card1_d : 'Барлық жеткізілімдер ресми рәсімделеді. Жасырын төлемсіз мөлдір шарттар.',
      why_card2_t : 'Нақты жеткізілімдер',  
      why_card2_d : 'Біз нақты техникалармен жұмыс жасаймыз. Жүктеу, қойма және жеткізу фотосуреттері мен бейнелері.',
      why_card3_t : 'Мөлдір есептеу',
      why_card3_d : 'Калькулятор сіз төлейтін төлемдерді көрсетеді. «Кейінірек қосымша төлемдер» жоқ.',
      why_card4_t : 'Бюджетке сай таңдау',
      why_card4_d : 'Біз «бар нәрсені» сатпай, тапсырма мен бюджетке сай техниканы таңдаймыз.',
      why_card5_t : 'Тіркеуге дейінгі қолдау',
      why_card5_d : 'Құжаттармен, кеденмен және тіркеумен көмек көрсетеміз.',
      footer_terms: 'Пайдаланушы келісімі',
      footer_privacy: 'Құпиялылық саясаты',
      loading: 'Жүктелуде...',
      loading_error: 'Каталогты жүктеу қатесі',
      body_all: 'Все типы',

      body_trailer: 'Тіркемелер',
      body_semitrailer: 'Жартылай тіркемелер', 
      body_dumptruck: 'Самосвал',
      body_tugboat:   'Тягач',

      body_specialequipment: 'Арнайы жабдықтар',
      body_crane:   'Түрту',
      body_manipulator: 'Манипулятор',
      body_mixer: 'Миксер',
      body_fuel_tank: 'Жанармай құю станциясы',
      body_aerial_ladder: 'Әуе платформасы',
      body_sewer_cleaner: 'Ассенизатор',

      body_refrigerator: 'Тоңазытқыш',
      body_van: 'Кемпер фургоны',
      body_sprinkler: 'Суару машинасы',
      body_drilling_rig: 'Бұрғылау қондырғысы',
      body_milk_truck: 'Сүт таситын машина',
      body_fuel_truck: 'Жанармай құю станциясы',

      calc_item_sbkts: 'СБКТС',
      calc_item_sos: 'SOS түймесі',
      calc_item_customs_fee: 'Кедендік алым',
      calc_item_broker_svh: 'СВХ-тағы брокер қызметі',
      calc_item_svh: 'СВХ',
      calc_item_border_broker: 'Шекарадағы брокер',
      calc_item_epts: 'ЭПТС',
      calc_item_diesel_pack: 'Дизель + AdBlue пакеті',
      calc_item_red_corridor: 'Дәліз',
      calc_item_thanks_astana: '«Астанаға рахмет»',
      calc_item_driver: 'Жүргізуші',
      calc_item_insurance: 'Сақтандыру',
      calc_item_toll_road: 'Ақылы жол',

      calc_item_declaration: 'Сәйкестік декларациясы',
      calc_item_customs_broker: 'Кедендік брокер',
      calc_item_driver: 'Жүргізуші',
      calc_item_adblue: 'AdBlue',
      calc_item_toll_road: 'Ақылы жол',
      calc_item_diesel: 'Дизель',
      calc_item_plate: 'Мемлекеттік нөмір және техникалық төлқұжат',
      calc_item_util_tax: 'Утилизациялық алым',
      calc_item_first_reg: 'Бастапқы тіркеу',
      calc_item_srtc: 'Техникалық төлқұжат (СРТС)',
      calc_flag_intl_carrier: 'Халықаралық тасымалдаушы куәлігі бар (тартқыштар үшін 7 жасқа дейін бастапқы тіркеу алынбайды)',

      // TOTAL LABELS
      calc_total_vehicle: 'Көлік құны',
      calc_total_clearance: 'Рәсімдеу құны',
      calc_total_turnkey: 'Толық құны',
      calc_year_label: 'Жылы',
      calc_item_broker_service: 'СВХ-дағы брокерлік қызметтер',
      calc_disclaimer: '⚠️ Есептеу алдын ала болып табылады және ашық ұсыныс емес. Соңғы құн валюта бағамдарына, кедендік төлемдерге және жеткізу шарттарына байланысты. Толығырақ менеджерден біліңіз.',
      body_car: 'Жеңіл көлік',
      calc_ts_bill_duty_percent: 'Баж ставкасы',
      why_card1_y: '✔ Келісімшарт бойынша жұмыс',
      why_card2_y: '✔ Жүктеу және жеткізу фотосуреттері мен бейнелері',
      why_card3_y: '✔ «Кейінірек қосымша төлемдер» жоқ мөлдір есептеу',
      why_card4_y: '✔ Кеден және тіркеуге көмек',
      btn_calculate_catalog: 'Толығырақ және есептеу',
    },

    zh: {
      reviews_title1: '客户处设备',
      reviews_title2: '新车客户',
      reviews_title3: '客户对卡车送货的反馈',
      nav_home: '首页',
      nav_catalog: '目录',
      nav_services: '服务',
      nav_contacts: '联系',
      nav_calculator: '计算器',
      nav_login: '登录',
      nav_account: '个人中心',
      nav_not_verified: '未验证',
      nav_logout_confirm: '确定要退出登录吗？',
      title_register: 'China Motors - 注册',
      title_login: 'China Motors - 登录',
      register_hero: '注册',
      register_tagline: '创建 China Motors 客户账户',
      register_tab_person: '个人',
      register_tab_company: '公司',
      register_person_note: '个人可以购买乘用车。购买商用车请使用公司注册。',
      register_company_note: '公司可以购买各种商用车辆。',
      register_phone_label: '电话',
      register_password_label: '密码',
      register_fullname_label: '姓名',
      register_iin_label: '身份识别号（IIN，用于合同）',
      register_companyname_label: '公司名称',
      register_bin_label: '商业识别号（BIN，用于合同）',
      register_address_label: '法定地址',
      register_submit: '创建账户',
      register_have_account: '已有账户？登录',
      register_err_required: '请填写必填项',
      register_success: '注册完成！账户正在等待管理员验证。',
      login_hero: '登录',
      login_tagline: '登录您的 China Motors 个人中心',
      login_submit: '登录',
      login_no_account: '没有账户？注册',
      login_success: '登录成功！',
      register_tab_service: '服务合作伙伴（保税仓）',
      register_tab_bank: '银行',
      register_tab_partner: '卖方合作伙伴（中国）',
      register_service_note: '请选择角色。账户将等待管理员验证。',
      register_service_role_label: '角色',
      register_service_role_placeholder: '— 请选择 —',
      register_role_declarant: '报关员（边境）',
      register_role_logistic: '物流',
      register_role_lab: '实验室',
      register_role_svh: '保税仓',
      register_role_broker: '经纪人（保税仓）',
      register_bank_note: '银行账户用于配合交易结算。',
      register_bankname_label: '银行名称',
      register_bik_label: '银行代码（BIK）',
      register_partner_note: '合作伙伴将获得账户并上传车辆信息 — 需经管理员审核。',
      register_country_label: '国家',
      register_regno_label: '公司注册号（用于合同）',
      title_account: 'China Motors - 个人中心',
      account_hero: '个人中心',
      account_logout: '退出',
      account_loading: '加载中...',
      account_my_listings_title: '我的信息',
      account_new_listing: '发布信息',
      account_listing_brand_label: '品牌',
      account_listing_title_label: '名称/型号',
      account_listing_category_label: '类别',
      account_listing_city_label: '城市',
      account_listing_weight_label: '重量(吨)',
      account_listing_power_label: '发动机功率(马力)',
      account_listing_load_capacity_label: '载重(吨)',
      account_listing_price_kzt_label: '价格(坚戈)',
      account_listing_photos_label: '照片',
      account_listing_description_label: '描述',
      badge_user_listing_prefix: '来自',
      product_create_deal: '办理交易',

      brand_title: 'China Motors',
      hero_title_main: '来自中国的专用设备和汽车,一站式服务',
      hero_tagline: '选型 • 核算 • 运输 • 清关 • 哈萨克斯坦注册上牌',
      hp_hero_badge: '中国工厂直接供货',
      hp_bullet1: '正式合同',
      hp_bullet2: '银行保障资金安全',
      hp_bullet3: '完整证件',
      hp_bullet4: '始于2018年',
      hp_cta_offer: '获取报价',
      hp_cta_catalog: '查看目录 →',
      hp_calc_widget_title: '计算费用',
      hp_calc_category: '类别',
      hp_calc_brand: '品牌',
      hp_calc_submit: '计算费用',
      hp_calc_widget_note: '免费且不承担任何义务',
      hp_process_title: '交易流程',
      hp_step1_t: '选择设备',
      hp_step1_d: '根据需求和预算挑选型号',
      hp_step2_t: '商业报价',
      hp_step2_d: '提供完整规格的费用核算',
      hp_step3_t: '合同与付款',
      hp_step3_d: '通过银行安全付款,提供完整证件',
      hp_step4_t: '运输与清关',
      hp_step4_d: '从中国运输并办理清关手续',
      hp_step5_t: '提车',
      hp_step5_d: '交付设备及全套证件',
      hp_vehicles_title: '热门设备',
      hp_vehicles_link: '查看完整目录 →',
      hp_vehicles_loading: '加载中...',
      hp_vehicle_cta: '获取报价',
      hp_stats_label: '值得信赖',
      hp_stat1: '客户',
      hp_stat2: '合作工厂',
      hp_stat3: '交付设备',
      hp_stat4: '经验',
      hp_stat4_years: '年',
      footer_address_khorgos: '霍尔果斯市 — 仓库与发货',
      footer_address_almaty: '阿拉木图市 — 设备提取',
      footer_col1_text: '来自中国的可靠设备，可现货或订购。',
      footer_col2_title: '导航',
      footer_col3_title: '联系方式',
      footer_copy: '© 2026 China Motors. 保留所有权利。',
      footer_devnote: '网站上的信息仅供参考，不构成公开报价',
      btn_photos: '照片',
      btn_calculate: '计算',
      btn_send: '发送',
      btn_refresh_rate: '刷新汇率',
      search_placeholder: '搜索…',

      about_title: '关于我们',
      about_p1: 'China Motors——来自中国霍尔果斯的车辆与专用设备供应商。自2024年起，我们提供高质量车辆并协助清关与运输。',
      about_p2: '我们的使命是以合理价格为客户提供高品质设备并保证质量。',
      about_card1_t: '选择丰富',
      about_card1_d: '多种专用设备型号。',
      about_card2_t: '个性化服务',
      about_card2_d: '充分考虑客户需求。',
      about_card3_t: '可靠运输',
      about_card3_d: '从霍尔果斯到阿拉木图。',
      about_card4_t: '透明办理',
      about_card4_d: '全流程文件支持。',
      about_card5_t: '价格',
      about_card5_d: '较低加价。',
      gallery_title: '画廊',
      gallery_cap1: '挂车',
      gallery_cap2: '半挂车',
      gallery_cap3: '拖车',
      gallery_cap4: '自卸车',
      gallery_cap5: '牵引车',
      gallery_cap6: '专用设备',
      gallery_cap7: '其他订制车辆',

      title_catalog: 'China Motors - 目录',
      catalog_hero: '数据库中的最新优惠',
      filter_body_label: '车型',
      filter_source_label: '来源',
      filter_source_all: '全部信息',
      filter_source_official: '官方目录',
      filter_source_user: '客户发布',
      filter_sort_label: '排序',
      sort_none: '无排序',
      sort_price_asc: '价格 ↑',
      sort_price_desc: '价格 ↓',
      card_body_label: '车型:',
      card_wheel_formula_label: '轮轴配置:',
      card_gearbox_label: '变速箱:',
      price_on_request: '价格面议',

      title_services: 'China Motors - 服务',
      services_hero: '我们的服务',
      services_tagline: '设备供应与维护一体化方案',
      services_title: '服务',
      service_1_t: '订购与供应',
      service_1_d: '按需从中国采购车辆与设备。',
      service_2_t: '清关',
      service_2_d: '协助海关手续。',
      service_3_t: '运输',
      service_3_d: '从霍尔果斯到阿拉木图（付费司机）。',
      service_4_t: '车牌',
      service_4_d: '协助办理车牌。',

      title_calculator: 'China Motors - 计算器',
      calculator_hero: '计算器',
      calculator_tagline: '一站式选购、运输与办理——2分钟内计算费用',
      calc_page_title: '成本计算器',
      calc_in_title: '输入数据',
      calc_in_name_label: '车型 / 配置',
      calc_in_name_ph: '例如：2022年牵引车',
      calc_in_price_label: '车辆价格, $',
      calc_in_price_ph: '59165',
      calc_in_type_label: '车型',
      calc_in_rate_label: '汇率 $ → ₸',
      calc_rate_info: '哈萨克国家银行汇率：—',
      calc_real_title: '1) 实际成本',
      calc_real_hint: '以坚戈计价 = 美元 × 汇率',
      calc_ts_title: '2) 海关计价',
      calc_ts_mode: '计价方式',
      calc_mode_byprice: '按全价',
      calc_mode_grid: '按年网格',
      calc_mode_fixed: '固定网格',
      calc_ts_usd_manual: '固定网格的计价, $',
      calc_ts_year_label: '年份（网格）',
      calc_ts_year_usd: '固定金额, $',
      calc_ts_bill_title: '关税费用',
      calc_ts_bill_ts: '海关计价(₸)',
      calc_ts_bill_duty: '关税',
      calc_ts_bill_vat: '增值税',
      calc_mand_title: '3) 额外费用',
      calc_mand_note: '取决于车型与计价模式。',
      calc_mand_list_title: '费用构成',
      calc_ship_title: '4) 运输与边境',
      calc_ship_list_title: '组成',
      calc_util_title: '5) 回收费与注册',
      calc_util_list_title: '政府费用',
      aside_title: '总计',
      aside_base: '计算基数：',
      aside_customs: '关税费用：',
      aside_mand: '额外费用：',
      aside_border: '运输与边境：',
      aside_util: '回收费/注册：',
      aside_total: '合计：',
      aside_usd: '≈ — USD',
      aside_btn_calc: '计算',
      aside_btn_apply: '提交申请',

      title_contacts: 'China Motors - 联系',
      contacts_hero: '联系',
      contacts_tagline: '以便捷方式与我们联系',
      contact_title: '提交申请',
      contact_name_label: '您的姓名',
      contact_name_ph: '请输入姓名',
      contact_phone_label: '电话',
      contact_phone_ph: '+7 (___) ___-__-__',
      contact_msg_label: '信息',
      contact_msg_ph: '您的信息',
      contact_note: '点击“发送”后，申请会直接到我们的Telegram',

      js_price_on_request: '价格面议',
      js_form_err_phone: '请输入正确的电话号码',
      js_form_err_msg: '请填写消息',
      js_form_sending: '发送中...',
      js_form_sent_ok: '已发送！我们会联系您。',
      js_form_sent_fail: '发送失败，请稍后再试。',
      why_title : '为什么选择我们',
      why_card1_t : '合同合作',
      why_card1_d : '所有供应均正式办理。透明条款，无隐藏费用。',
      why_card2_t : '实际供应',
      why_card2_d : '我们处理实际设备。装载、仓库和交付的照片和视频。',
      why_card3_t : '透明计算',
      why_card3_d : '计算器显示您支付的费用。没有“之后再付钱”。',
      why_card4_t : '根据预算选择',
      why_card4_d : '根据任务和预算选择设备，而不是出售“现有”设备。',
      why_card5_t : '注册支持',
      why_card5_d : '我们协助处理文件、海关和注册。',
      footer_terms: '用户协议',
      footer_privacy: '隐私政策',
      loading: '加载中...',
      loading_error: '目录加载错误',
      body_all: '所有类型',

      body_trailer: '挂车',
      body_semitrailer: '半挂车',
      body_dumptruck: '自卸车',
      body_tugboat: '牵引车',

      body_specialequipment: '专用设备',
      body_crane: '起重机',
      body_manipulator: '操作器',       
      body_mixer: '搅拌机',
      body_fuel_tank: '油罐车',
      body_aerial_ladder: '高空作业车',
      body_sewer_cleaner: '清污车',

      body_refrigerator: '冷藏车',
      body_van: '厢式货车',
      body_sprinkler: '洒水车',
      body_drilling_rig: '钻机',
      body_milk_truck: '运奶车',
      body_fuel_truck: '加油车',

      calc_item_sbkts: 'SBKTS 证书',
      calc_item_sos: 'SOS 按钮',
      calc_item_customs_fee: '海关费用',
      calc_item_broker_svh: '仓储区经纪服务',
      calc_item_svh: '仓储区',
      calc_item_border_broker: '边境代理',
      calc_item_epts: '电子车辆护照',
      calc_item_diesel_pack: '柴油 + AdBlue 套餐',
      calc_item_red_corridor: '通道',
      calc_item_thanks_astana: '“感谢阿斯塔纳”',
      calc_item_driver: '司机',
      calc_item_insurance: '保险',
      calc_item_toll_road: '收费公路',

      calc_item_declaration: '符合性声明',
      calc_item_customs_broker: '海关代理',
      calc_item_driver: '司机',
      calc_item_adblue: 'AdBlue',
      calc_item_toll_road: '收费公路',
      calc_item_diesel: '柴油',
      calc_item_plate: '车牌和技术护照',
      calc_item_util_tax: '回收费',
      calc_item_first_reg: '首次注册',
      calc_item_srtc: '技术护照（SRTC）',
      calc_flag_intl_carrier: '持有国际承运人证书（7年以内牵引车免收首次注册费）',

      // TOTAL LABELS
      calc_total_vehicle: '车辆价格',
      calc_total_clearance: '清关费用',
      calc_total_turnkey: '交钥匙总价',
      calc_year_label: '出厂年份',
      calc_item_broker_service: '保税仓经纪服务',
      calc_disclaimer: '⚠️ 计算结果为预估值，非公开报价。最终价格取决于汇率、关税和供应条件。详情请咨询经理。',
      body_car: '乘用车',
      calc_ts_bill_duty_percent: '关税税率',
      why_card1_y: '✔ 合同合作',
      why_card2_y: '✔ 装载和交付的照片与视频',
      why_card3_y: '✔ 没有“之后再付钱”的透明计算',
      why_card4_y: '✔ 协助海关和注册',
      btn_calculate_catalog: '详情与计算',
    },

    en: {
      reviews_title1: 'Equipment at the clients place',
      reviews_title2: 'Customer with a new car',
      reviews_title3: 'Customer feedback on truck delivery',
      nav_home: 'Home',
      nav_catalog: 'Catalog',
      nav_services: 'Services',
      nav_contacts: 'Contacts',
      nav_calculator: 'Calculator',
      nav_login: 'Log in',
      nav_account: 'Account',
      nav_not_verified: 'not verified',
      nav_logout_confirm: 'Log out of your account?',
      title_register: 'China Motors - Register',
      title_login: 'China Motors - Login',
      register_hero: 'Register',
      register_tagline: 'Create a China Motors customer account',
      register_tab_person: 'Individual',
      register_tab_company: 'Company',
      register_person_note: 'Individuals can purchase a passenger car. For commercial vehicles, please register as a company.',
      register_company_note: 'Companies can purchase various types of commercial vehicles.',
      register_phone_label: 'Phone',
      register_password_label: 'Password',
      register_fullname_label: 'Full name',
      register_iin_label: 'IIN (for the contract)',
      register_companyname_label: 'Company name',
      register_bin_label: 'BIN (for the contract)',
      register_address_label: 'Legal address',
      register_submit: 'Create account',
      register_have_account: 'Already have an account? Log in',
      register_err_required: 'Please fill in the required fields',
      register_success: 'Registration complete! Your account is awaiting admin verification.',
      login_hero: 'Login',
      login_tagline: 'Log in to your China Motors account',
      login_submit: 'Log in',
      login_no_account: "Don't have an account? Register",
      login_success: 'Logged in successfully!',
      register_tab_service: 'Service partner (SVH)',
      register_tab_bank: 'Bank',
      register_tab_partner: 'Seller partner (China)',
      register_service_note: 'Choose a role. The account will await admin verification.',
      register_service_role_label: 'Role',
      register_service_role_placeholder: '— select —',
      register_role_declarant: 'Declarant (border)',
      register_role_logistic: 'Logistics',
      register_role_lab: 'Laboratory',
      register_role_svh: 'SVH (bonded warehouse)',
      register_role_broker: 'Broker (SVH)',
      register_bank_note: "The bank account is used to support the deal's settlement process.",
      register_bankname_label: 'Bank name',
      register_bik_label: 'BIK',
      register_partner_note: 'Partners get a dashboard and upload vehicle listings — subject to admin moderation.',
      register_country_label: 'Country',
      register_regno_label: 'Company registration number (for the contract)',
      title_account: 'China Motors - Account',
      account_hero: 'Account',
      account_logout: 'Log out',
      account_loading: 'Loading...',
      account_my_listings_title: 'My listings',
      account_new_listing: 'Post a listing',
      account_listing_brand_label: 'Brand',
      account_listing_title_label: 'Title / model',
      account_listing_category_label: 'Category',
      account_listing_city_label: 'City',
      account_listing_weight_label: 'Weight, t',
      account_listing_power_label: 'Engine power, hp',
      account_listing_load_capacity_label: 'Load capacity, t',
      account_listing_price_kzt_label: 'Price, KZT',
      account_listing_photos_label: 'Photos',
      account_listing_description_label: 'Description',
      badge_user_listing_prefix: 'Listed by',
      product_create_deal: 'Create a deal',

      brand_title: 'China Motors',
      hero_title_main: 'Special equipment and vehicles from China, turnkey',
      hero_tagline: 'Selection • calculation • delivery • customs • registration in Kazakhstan',
      hp_hero_badge: 'DIRECT SUPPLY FROM CHINESE FACTORIES',
      hp_bullet1: 'Official contract',
      hp_bullet2: 'Bank protects your money',
      hp_bullet3: 'Full set of documents',
      hp_bullet4: 'Since 2018',
      hp_cta_offer: 'Get a quote',
      hp_cta_catalog: 'View catalog →',
      hp_calc_widget_title: 'Calculate the cost',
      hp_calc_category: 'Category',
      hp_calc_brand: 'Brand',
      hp_calc_submit: 'Calculate the cost',
      hp_calc_widget_note: 'free and non-binding',
      hp_process_title: 'How the deal works',
      hp_step1_t: 'Choosing equipment',
      hp_step1_d: 'We pick a model to fit your needs and budget',
      hp_step2_t: 'Commercial offer',
      hp_step2_d: 'Cost calculation with full specification',
      hp_step3_t: 'Contract and payment',
      hp_step3_d: 'Secure payment through the bank, full set of documents',
      hp_step4_t: 'Delivery and customs',
      hp_step4_d: 'Logistics from China and customs clearance',
      hp_step5_t: 'Receiving the equipment',
      hp_step5_d: 'Handover of the equipment and full set of documents',
      hp_vehicles_title: 'Popular equipment',
      hp_vehicles_link: 'View full catalog →',
      hp_vehicles_loading: 'Loading...',
      hp_vehicle_cta: 'Get a quote',
      hp_stats_label: 'TRUSTED BY',
      hp_stat1: 'customers',
      hp_stat2: 'partner factories',
      hp_stat3: 'units delivered',
      hp_stat4: 'of work',
      hp_stat4_years: 'years',
      footer_address_khorgos: 'Khorgos — warehouse and shipping',
      footer_address_almaty: 'Almaty — equipment pickup',
      footer_col1_text: 'Reliable vehicles from China — in stock and on order.',
      footer_col2_title: 'Navigation',
      footer_col3_title: 'Contacts',
      footer_copy: '© 2026 China Motors. All rights reserved.',
      footer_devnote: 'Information on the site is for reference only and does not constitute a public offer',
      btn_photos: 'Photos',
      btn_calculate: 'Calculate',
      btn_send: 'Send',
      btn_refresh_rate: 'Refresh rate',
      search_placeholder: 'Search...',

      about_title: 'About us',
      about_p1: 'China Motors is your reliable partner for sourcing cars and special equipment from Khorgos, China. Since 2024 we provide quality vehicles and professional logistics & customs support.',
      about_p2: 'Our mission is to deliver modern equipment at fair prices with guaranteed quality.',
      about_card1_t: 'Wide selection',
      about_card1_d: 'Various models of special equipment.',
      about_card2_t: 'Personal approach',
      about_card2_d: 'We consider all client requirements.',
      about_card3_t: 'Reliable delivery',
      about_card3_d: 'From Khorgos to Almaty.',
      about_card4_t: 'Transparent paperwork',
      about_card4_d: 'Full document support.',
      about_card5_t: 'Price',
      about_card5_d: 'Low markup.',
      gallery_title: 'Gallery',
      gallery_cap1: 'Trailers',
      gallery_cap2: 'Semi-trailers',
      gallery_cap3: 'Lowboys',
      gallery_cap4: 'Dump trucks',
      gallery_cap5: 'Tractors',
      gallery_cap6: 'Special equipment',
      gallery_cap7: 'Other vehicles on request',
      reviews_title: 'Reviews',

      title_catalog: 'China Motors - Catalog',
      catalog_hero: 'Latest offers from the database',
      filter_body_label: 'Vehicle type',
      filter_source_label: 'Source',
      filter_source_all: 'All listings',
      filter_source_official: 'Official catalog',
      filter_source_user: 'Customer listings',
      filter_sort_label: 'Sort',
      sort_none: 'No sorting',
      sort_price_asc: 'Price ↑',
      sort_price_desc: 'Price ↓',
      card_body_label: 'Vehicle type:',
      card_wheel_formula_label: 'Wheel formula:',
      card_gearbox_label: 'Gearbox:',
      price_on_request: 'Price on request',

      title_services: 'China Motors - Services',
      services_hero: 'Our services',
      services_tagline: 'End-to-end solutions for supply and maintenance',
      services_title: 'Services',
      service_1_t: 'Ordering & supply',
      service_1_d: 'Vehicles and equipment from China for your needs.',
      service_2_t: 'Customs clearance',
      service_2_d: 'Assistance with customs procedures.',
      service_3_t: 'Delivery',
      service_3_d: 'From Khorgos to Almaty (paid drivers).',
      service_4_t: 'License plate',
      service_4_d: 'Assistance with plate issuance.',

      title_calculator: 'China Motors - Calculator',
      calculator_hero: 'Calculator',
      calculator_tagline: 'One-stop cost calculation for ordering, delivery, and paperwork — in 2 minutes',
      calc_page_title: 'Cost calculator',
      calc_in_title: 'Input data',
      calc_in_name_label: 'Model / configuration',
      calc_in_name_ph: 'e.g., Tractor 2022',
      calc_in_price_label: 'Vehicle price, $',
      calc_in_price_ph: '59165',
      calc_in_type_label: 'Vehicle type',
      calc_in_rate_label: 'Rate $ → ₸',
      calc_rate_info: 'NBK official rate: —',
      calc_real_title: '1) Actual cost',
      calc_real_hint: 'Price in KZT = USD × Rate',
      calc_ts_title: '2) Customs value',
      calc_ts_mode: 'Customs mode',
      calc_mode_byprice: 'By full price',
      calc_mode_grid: 'Grid (year)',
      calc_mode_fixed: 'Fixed grid',
      calc_ts_usd_manual: 'Customs, $ (for Fixed grid)',
      calc_ts_year_label: 'Year (for Grid)',
      calc_ts_year_usd: 'Fixed amount, $',
      calc_ts_bill_title: 'Customs charges',
      calc_ts_bill_ts: 'Customs value (₸)',
      calc_ts_bill_duty: 'Duty',
      calc_ts_bill_vat: 'VAT',
      calc_mand_title: '3) Additional expenses',
      calc_mand_note: 'Depends on vehicle type and chosen mode.',
      calc_mand_list_title: 'Breakdown',
      calc_ship_title: '4) Delivery & border',
      calc_ship_list_title: 'Delivery includes',
      calc_util_title: '5) Recycling fee & registration',
      calc_util_list_title: 'Government payments',
      aside_title: 'Total cost',
      aside_base: 'Base:',
      aside_customs: 'Customs:',
      aside_mand: 'Additional:',
      aside_border: 'Delivery & border:',
      aside_util: 'Recycling/registration:',
      aside_total: 'TOTAL:',
      aside_usd: '≈ — USD',
      aside_btn_calc: 'Calculate',
      aside_btn_apply: 'Submit request',

      title_contacts: 'China Motors - Contacts',
      contacts_hero: 'Contacts',
      contacts_tagline: 'Contact us in a convenient way',
      contact_title: 'Leave a request',
      contact_name_label: 'Your name',
      contact_name_ph: 'Enter your name',
      contact_phone_label: 'Phone',
      contact_phone_ph: '+7 (___) ___-__-__',
      contact_msg_label: 'Message',
      contact_msg_ph: 'Your message',
      contact_note: 'After clicking “Send”, your request goes to our Telegram',

      js_price_on_request: 'Price on request',
      js_form_err_phone: 'Enter a valid phone number',
      js_form_err_msg: 'Add a message',
      js_form_sending: 'Sending...',
      js_form_sent_ok: 'Request sent! We will contact you.',
      js_form_sent_fail: 'Sending failed. Try again later.',
      why_title : 'Why choose us',
      why_card1_t : 'Contract cooperation',
      why_card1_d : 'All supplies are formally processed. Transparent terms, no hidden fees.',
      why_card2_t : 'Actual supply',
      why_card2_d : 'We handle actual equipment. Photos and videos of loading, warehousing, and delivery.',
      why_card3_t : 'Transparent calculation',
      why_card3_d : 'The calculator shows what you pay for. No "pay later".',
      why_card4_t : 'Choose by budget',
      why_card4_d : 'Select equipment based on task and budget, not selling "available" equipment.',
      why_card5_t : 'Registration support',
      why_card5_d : 'We assist with paperwork, customs, and registration.',
      footer_terms: 'User Agreement',
      footer_privacy: 'Privacy Policy',
      loading: 'Loading...',
      loading_error: 'Catalog loading error',
      
      body_trailer: "Trailer",
      body_semitrailer: "Semi-trailer",
      body_dumptruck: "Dump Truck",
      body_tugboat: "Tractor Unit",

      body_specialequipment: "Special Equipment",
      body_crane: "Crane",
      body_manipulator: "Truck Crane (Manipulator)",
      body_mixer: "Concrete Mixer",
      body_fuel_tank: "Fuel Tank Truck",
      body_aerial_ladder: "Aerial Platform",
      body_sewer_cleaner: "Sewage Truck",

      body_refrigerator: "Refrigerated Truck",
      body_van: "Cargo Van",
      body_sprinkler: "Water Sprinkler Truck",

      body_drilling_rig: "Drilling Rig Truck",
      body_milk_truck: "Milk Tank Truck",
      body_fuel_truck: "Fuel Refuel Truck",

      body_all: 'All types',
      calc_item_sbkts: 'SBKTS certificate',
      calc_item_sos: 'SOS button',
      calc_item_customs_fee: 'Customs fee',
      calc_item_broker_svh: 'SVH broker services',
      calc_item_svh: 'SVH',
      calc_item_border_broker: 'Border broker',
      calc_item_epts: 'EPTS',
      calc_item_diesel_pack: 'Diesel + AdBlue package',
      calc_item_red_corridor: 'Corridor',
      calc_item_thanks_astana: '“Thanks to Astana”',
      calc_item_driver: 'Driver',
      calc_item_insurance: 'Insurance',
      calc_item_toll_road: 'Toll road',

      calc_item_declaration: 'Declaration of conformity',
      calc_item_customs_broker: 'Customs broker',
      calc_item_driver: 'Driver',
      calc_item_adblue: 'AdBlue',
      calc_item_toll_road: 'Toll road',
      calc_item_diesel: 'Diesel',
      calc_item_plate: 'License plate and technical passport',
      calc_item_util_tax: 'Recycling fee',
      calc_item_first_reg: 'Initial registration',
      calc_item_srtc: 'Technical passport (SRTC)',
      calc_flag_intl_carrier: 'Has international carrier permit (primary registration waived for tractors under 7 years old)',

      // TOTAL LABELS
      calc_total_vehicle: 'Vehicle price',
      calc_total_clearance: 'Clearance cost',
      calc_total_turnkey: 'Turnkey total',
      calc_year_label: 'Year',
      calc_item_broker_service: 'SVH broker services',
      calc_disclaimer: '⚠️ Calculation is preliminary and not a public offer. Final cost depends on exchange rates, customs duties, and delivery terms. Consult the manager for details.',
      body_car: 'Car',
      calc_ts_bill_duty_percent: 'Duty rate',
      why_card1_y: '✔ Contract cooperation',
      why_card2_y: '✔ Photos and videos of loading and delivery',
      why_card3_y: '✔ Transparent calculation with no "pay later"',
      why_card4_y: '✔ Assistance with customs and registration',
      btn_calculate_catalog: 'Details and calculation',
    },
  };
  window.translations = translations;
  function getLang() {
    return localStorage.getItem(LS_LANG) || 'ru';
  }

  function applyLang(lang) {
    document.documentElement.lang = lang;

    // обычный текст
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.dataset.i18n;
      const value = translations[lang]?.[key];
      if (value) el.textContent = value;
    });

    // placeholder
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.dataset.i18nPlaceholder;
      const value = translations[lang]?.[key];
      if (value) el.placeholder = value;
    });

    localStorage.setItem('lang', lang);
  }


  /* =====================
     THEME (ТОЛЬКО CSS)
     ===================== */
  function initTheme() {
    const saved = localStorage.getItem(LS_THEME);
    if (saved === 'dark') {
      document.documentElement.classList.add('dark');
    }

    const themeBtn = document.getElementById('themeToggle');
    themeBtn?.addEventListener('click', () => {
      document.documentElement.classList.toggle('dark');
      localStorage.setItem(
        LS_THEME,
        document.documentElement.classList.contains('dark') ? 'dark' : 'light'
      );
    });
  }

  /* =====================
     LANGUAGE BUTTON
     ===================== */
  function initLang() {
    const langBtn = document.getElementById('langToggle');
    if (!langBtn) return;

    const order = ['ru', 'kk', 'en', 'zh'];
    let current = getLang();

    applyLang(current);
    langBtn.textContent = current.toUpperCase();
    
    langBtn.addEventListener('click', () => {
      current = order[(order.indexOf(current) + 1) % order.length];
      langBtn.textContent = current.toUpperCase();
      applyLang(current);

      if (typeof window.recalc === 'function') {
        window.recalc();
      }

    });


  }
  function initBurger() {
    const burger = document.querySelector('.menu-toggle');
    const navLinks = document.querySelector('.nav-links');

    if (!burger || !navLinks) return;

    burger.addEventListener('click', () => {
      navLinks.classList.toggle('active');
    });

    // закрытие меню при клике на пункт
    navLinks.querySelectorAll('a').forEach(link => {
      link.addEventListener('click', () => {
        navLinks.classList.remove('active');
      });
    });
  }

  // Показывает «Войти» или «Личный кабинет» в шапке — зависит от того,
  // залогинен ли клиент (js/auth.js, если подключён на странице).
  function initAuthNav() {
    const link = document.getElementById('navAuthLink');
    if (!link || !window.CMAuth) return;

    const session = window.CMAuth.getSession();
    const label = link.querySelector('span');

    if (session) {
      link.href = 'account.html';
      if (label) label.setAttribute('data-i18n', 'nav_account');
      label.textContent = session.isVerified
        ? window.t('nav_account')
        : `${window.t('nav_account')} (${window.t('nav_not_verified')})`;
      link.onclick = null;
    } else {
      link.href = 'login.html';
      if (label) {
        label.setAttribute('data-i18n', 'nav_login');
        label.textContent = window.t('nav_login');
      }
      link.onclick = null;
    }
  }

  /* =====================
     PARTIAL LOADER
     ===================== */
  async function loadPartial(targetId, url, callback) {
    const target = document.getElementById(targetId);
    if (!target) return;

    const res = await fetch(url);
    target.innerHTML = await res.text();
    if (callback) callback();
  }

  /* =====================
     INIT
     ===================== */
  document.addEventListener('DOMContentLoaded', () => {

    loadPartial('siteHeader', './partials/navbar.html', () => {
    initTheme();
    initLang();
    initBurger();
    initAuthNav();
  });


    loadPartial('siteFooter', './partials/footer.html', () => {
      applyLang(getLang());
    });

  });
  window.t = function (key) {
    const lang = localStorage.getItem('lang') || 'ru';
    return window.translations?.[lang]?.[key] || key;
  };
  function getLang() {
    const l = localStorage.getItem(LS_LANG);
    return translations[l] ? l : 'ru';
  }

  var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
  s1.async=true;
  s1.src='https://embed.tawk.to/68480dddb0d263190ae16f29/1itcncalg';
  s1.charset='UTF-8';
  s1.setAttribute('crossorigin','*');
  s0.parentNode.insertBefore(s1,s0);

  
})();



